### ISSUE TITLE
Timeout in check_output throws TypeError due to missing argument

### ISSUE THREAD

**Issue by lcmcninch** [google/python-subprocess32#9] opened 2016-04-22 17:37 UTC
In Popen._communicate, when TimeoutExpired is called (lines 1190 and 1194) the second argument (timeout) is omitted, resulting in a TypeError.

[subprocess32.zip](https://github.com/google/python-subprocess32/files/232302/subprocess32.zip)

EDIT: I'm moving too quickly today, basically a dupliate of https://github.com/google/python-subprocess32/issues/7

**Comment by gpshead** [comment] 2017-05-28 05:08
duplicate of #7

**Closed by gpshead** 2017-05-28 05:08 UTC
